import type { FacultyLeaveApprovalData } from '../types/leaveApproval';

// ============================================
// Mock data for /hod/faculty-leave-approval route
// Used as fallback when backend is unavailable
// ============================================

export const MOCK_FACULTY_LEAVE_APPROVAL_DATA: FacultyLeaveApprovalData = {
    departmentName: 'Computer Science & Engineering',
    academicYear: '2025–2026',
    summaryStats: {
        totalRequests: 14,
        pendingCount: 5,
        approvedCount: 7,
        rejectedCount: 2,
        totalDaysRequested: 31,
        avgDaysPerRequest: 2.2,
    },
    leaveRequests: [
        {
            id: 1,
            facultyId: 'f-001',
            facultyName: 'Dr. Anitha Rajan',
            employeeId: 'CSE001',
            designation: 'Associate Professor',
            department: 'CSE',
            profilePhoto: null,
            leaveType: 'CASUAL',
            startDate: '2026-03-10',
            endDate: '2026-03-11',
            totalDays: 2,
            reason: 'Attending family function',
            status: 'PENDING',
            appliedOn: '2026-03-02',
            actionTakenOn: null,
            actionTakenBy: null,
            rejectionRemark: null,
            approvalRemark: null,
            casualLeaveBalance: 8,
            sickLeaveBalance: 10,
            earnedLeaveBalance: 15,
        },
        {
            id: 2,
            facultyId: 'f-002',
            facultyName: 'Prof. Karthik Subramanian',
            employeeId: 'CSE002',
            designation: 'Assistant Professor',
            department: 'CSE',
            profilePhoto: null,
            leaveType: 'SICK',
            startDate: '2026-02-20',
            endDate: '2026-02-21',
            totalDays: 2,
            reason: 'Fever and throat infection, doctor advised rest',
            status: 'APPROVED',
            appliedOn: '2026-02-19',
            actionTakenOn: '2026-02-20',
            actionTakenBy: 'HOD - Dr. S. Venkatesh',
            rejectionRemark: null,
            approvalRemark: 'Get well soon. Ensure lecture plan is shared.',
            casualLeaveBalance: 10,
            sickLeaveBalance: 8,
            earnedLeaveBalance: 12,
        },
        {
            id: 3,
            facultyId: 'f-003',
            facultyName: 'Ms. Priya Venkataraman',
            employeeId: 'CSE003',
            designation: 'Assistant Professor',
            department: 'CSE',
            profilePhoto: null,
            leaveType: 'DUTY',
            startDate: '2026-03-15',
            endDate: '2026-03-17',
            totalDays: 3,
            reason: 'Attending national conference on AI at IIT Madras',
            status: 'PENDING',
            appliedOn: '2026-03-01',
            actionTakenOn: null,
            actionTakenBy: null,
            rejectionRemark: null,
            approvalRemark: null,
            casualLeaveBalance: 7,
            sickLeaveBalance: 10,
            earnedLeaveBalance: 18,
        },
        {
            id: 4,
            facultyId: 'f-004',
            facultyName: 'Dr. Ramesh Balasubramaniam',
            employeeId: 'CSE004',
            designation: 'Associate Professor',
            department: 'CSE',
            profilePhoto: null,
            leaveType: 'EARNED',
            startDate: '2026-03-20',
            endDate: '2026-03-24',
            totalDays: 5,
            reason: 'Annual family vacation planned in advance',
            status: 'APPROVED',
            appliedOn: '2026-02-25',
            actionTakenOn: '2026-02-27',
            actionTakenBy: 'HOD - Dr. S. Venkatesh',
            rejectionRemark: null,
            approvalRemark: 'Approved. Ensure all classes are covered.',
            casualLeaveBalance: 4,
            sickLeaveBalance: 10,
            earnedLeaveBalance: 10,
        },
        {
            id: 5,
            facultyId: 'f-005',
            facultyName: 'Mr. Suresh Kumar',
            employeeId: 'CSE005',
            designation: 'Assistant Professor',
            department: 'CSE',
            profilePhoto: null,
            leaveType: 'CASUAL',
            startDate: '2026-02-14',
            endDate: '2026-02-14',
            totalDays: 1,
            reason: 'Personal errand — bank work',
            status: 'REJECTED',
            appliedOn: '2026-02-13',
            actionTakenOn: '2026-02-13',
            actionTakenBy: 'HOD - Dr. S. Venkatesh',
            rejectionRemark: 'Applied too close to exam preparatory period. Please reschedule.',
            approvalRemark: null,
            casualLeaveBalance: 10,
            sickLeaveBalance: 10,
            earnedLeaveBalance: 20,
        },
        {
            id: 6,
            facultyId: 'f-001',
            facultyName: 'Dr. Anitha Rajan',
            employeeId: 'CSE001',
            designation: 'Associate Professor',
            department: 'CSE',
            profilePhoto: null,
            leaveType: 'SICK',
            startDate: '2026-01-28',
            endDate: '2026-01-30',
            totalDays: 3,
            reason: 'Migraine and prescribed bed rest',
            status: 'APPROVED',
            appliedOn: '2026-01-27',
            actionTakenOn: '2026-01-28',
            actionTakenBy: 'HOD - Dr. S. Venkatesh',
            rejectionRemark: null,
            approvalRemark: 'Approved.',
            casualLeaveBalance: 8,
            sickLeaveBalance: 7,
            earnedLeaveBalance: 15,
        },
        {
            id: 7,
            facultyId: 'f-006',
            facultyName: 'Dr. Meena Krishnamurthy',
            employeeId: 'CSE006',
            designation: 'Professor',
            department: 'CSE',
            profilePhoto: null,
            leaveType: 'MATERNITY',
            startDate: '2026-04-01',
            endDate: '2026-10-01',
            totalDays: 180,
            reason: 'Maternity leave',
            status: 'APPROVED',
            appliedOn: '2026-02-01',
            actionTakenOn: '2026-02-05',
            actionTakenBy: 'HOD - Dr. S. Venkatesh',
            rejectionRemark: null,
            approvalRemark: 'Approved as per institution policy.',
            casualLeaveBalance: 12,
            sickLeaveBalance: 10,
            earnedLeaveBalance: 22,
        },
        {
            id: 8,
            facultyId: 'f-007',
            facultyName: 'Mr. Vijay Anand',
            employeeId: 'CSE007',
            designation: 'Assistant Professor',
            department: 'CSE',
            profilePhoto: null,
            leaveType: 'CASUAL',
            startDate: '2026-03-06',
            endDate: '2026-03-07',
            totalDays: 2,
            reason: 'Sibling\'s wedding',
            status: 'PENDING',
            appliedOn: '2026-02-28',
            actionTakenOn: null,
            actionTakenBy: null,
            rejectionRemark: null,
            approvalRemark: null,
            casualLeaveBalance: 9,
            sickLeaveBalance: 10,
            earnedLeaveBalance: 14,
        },
        {
            id: 9,
            facultyId: 'f-008',
            facultyName: 'Dr. Lakshmi Narayanan',
            employeeId: 'CSE008',
            designation: 'Senior Assistant Professor',
            department: 'CSE',
            profilePhoto: null,
            leaveType: 'DUTY',
            startDate: '2026-03-08',
            endDate: '2026-03-08',
            totalDays: 1,
            reason: 'Paper presentation at state-level seminar',
            status: 'PENDING',
            appliedOn: '2026-03-01',
            actionTakenOn: null,
            actionTakenBy: null,
            rejectionRemark: null,
            approvalRemark: null,
            casualLeaveBalance: 6,
            sickLeaveBalance: 10,
            earnedLeaveBalance: 16,
        },
        {
            id: 10,
            facultyId: 'f-003',
            facultyName: 'Ms. Priya Venkataraman',
            employeeId: 'CSE003',
            designation: 'Assistant Professor',
            department: 'CSE',
            profilePhoto: null,
            leaveType: 'CASUAL',
            startDate: '2026-02-10',
            endDate: '2026-02-10',
            totalDays: 1,
            reason: 'Driving licence renewal',
            status: 'APPROVED',
            appliedOn: '2026-02-08',
            actionTakenOn: '2026-02-09',
            actionTakenBy: 'HOD - Dr. S. Venkatesh',
            rejectionRemark: null,
            approvalRemark: 'Approved.',
            casualLeaveBalance: 6,
            sickLeaveBalance: 10,
            earnedLeaveBalance: 18,
        },
        {
            id: 11,
            facultyId: 'f-005',
            facultyName: 'Mr. Suresh Kumar',
            employeeId: 'CSE005',
            designation: 'Assistant Professor',
            department: 'CSE',
            profilePhoto: null,
            leaveType: 'SICK',
            startDate: '2026-03-03',
            endDate: '2026-03-03',
            totalDays: 1,
            reason: 'Food poisoning — doctor prescription attached',
            status: 'PENDING',
            appliedOn: '2026-03-03',
            actionTakenOn: null,
            actionTakenBy: null,
            rejectionRemark: null,
            approvalRemark: null,
            casualLeaveBalance: 10,
            sickLeaveBalance: 9,
            earnedLeaveBalance: 20,
        },
        {
            id: 12,
            facultyId: 'f-002',
            facultyName: 'Prof. Karthik Subramanian',
            employeeId: 'CSE002',
            designation: 'Assistant Professor',
            department: 'CSE',
            profilePhoto: null,
            leaveType: 'EARNED',
            startDate: '2026-01-02',
            endDate: '2026-01-04',
            totalDays: 3,
            reason: 'Travel to hometown for Pongal festival',
            status: 'APPROVED',
            appliedOn: '2025-12-28',
            actionTakenOn: '2025-12-30',
            actionTakenBy: 'HOD - Dr. S. Venkatesh',
            rejectionRemark: null,
            approvalRemark: 'Approved. Happy Pongal.',
            casualLeaveBalance: 10,
            sickLeaveBalance: 10,
            earnedLeaveBalance: 15,
        },
        {
            id: 13,
            facultyId: 'f-007',
            facultyName: 'Mr. Vijay Anand',
            employeeId: 'CSE007',
            designation: 'Assistant Professor',
            department: 'CSE',
            profilePhoto: null,
            leaveType: 'SICK',
            startDate: '2026-02-05',
            endDate: '2026-02-06',
            totalDays: 2,
            reason: 'Viral fever',
            status: 'REJECTED',
            appliedOn: '2026-02-06',
            actionTakenOn: '2026-02-06',
            actionTakenBy: 'HOD - Dr. S. Venkatesh',
            rejectionRemark: 'Applied retrospectively without prior information. Please follow protocol.',
            approvalRemark: null,
            casualLeaveBalance: 9,
            sickLeaveBalance: 10,
            earnedLeaveBalance: 14,
        },
        {
            id: 14,
            facultyId: 'f-008',
            facultyName: 'Dr. Lakshmi Narayanan',
            employeeId: 'CSE008',
            designation: 'Senior Assistant Professor',
            department: 'CSE',
            profilePhoto: null,
            leaveType: 'CASUAL',
            startDate: '2026-02-27',
            endDate: '2026-02-28',
            totalDays: 2,
            reason: 'Attending daughter\'s school annual day',
            status: 'APPROVED',
            appliedOn: '2026-02-20',
            actionTakenOn: '2026-02-21',
            actionTakenBy: 'HOD - Dr. S. Venkatesh',
            rejectionRemark: null,
            approvalRemark: 'Approved.',
            casualLeaveBalance: 4,
            sickLeaveBalance: 10,
            earnedLeaveBalance: 16,
        },
    ],
};
