import type { FacultyWorkloadData } from '../types/workload';

// ============================================
// Mock data for /hod/faculty-workload route
// Used as fallback when backend is unavailable
// ============================================

export const MOCK_FACULTY_WORKLOAD_DATA: FacultyWorkloadData = {
    departmentName: 'Computer Science & Engineering',
    semesterLabel: 'Semester V — July–Nov 2025',
    summaryStats: {
        totalFaculty: 8,
        overloadedCount: 2,
        optimalCount: 5,
        underloadedCount: 1,
        avgHoursPerWeek: 17.5,
        totalCourseSections: 24,
    },
    facultyWorkloads: [
        {
            id: 1,
            facultyName: 'Dr. Anitha Rajan',
            employeeId: 'CSE001',
            designation: 'Associate Professor',
            department: 'CSE',
            profilePhoto: null,
            totalHoursPerWeek: 22,
            maxHoursPerWeek: 20,
            status: 'OVERLOADED',
            attendanceAvg: 91.4,
            pendingGradingCount: 3,
            courseAssignments: [
                {
                    id: 101,
                    subjectName: 'Data Structures & Algorithms',
                    subjectCode: 'CS301',
                    sectionName: 'CSE-A',
                    semester: 3,
                    hoursPerWeek: 5,
                    studentCount: 62,
                    department: 'CSE',
                },
                {
                    id: 102,
                    subjectName: 'Data Structures & Algorithms',
                    subjectCode: 'CS301',
                    sectionName: 'CSE-B',
                    semester: 3,
                    hoursPerWeek: 5,
                    studentCount: 58,
                    department: 'CSE',
                },
                {
                    id: 103,
                    subjectName: 'Design & Analysis of Algorithms',
                    subjectCode: 'CS501',
                    sectionName: 'CSE-A',
                    semester: 5,
                    hoursPerWeek: 4,
                    studentCount: 60,
                    department: 'CSE',
                },
                {
                    id: 104,
                    subjectName: 'Design & Analysis of Algorithms',
                    subjectCode: 'CS501',
                    sectionName: 'CSE-B',
                    semester: 5,
                    hoursPerWeek: 4,
                    studentCount: 55,
                    department: 'CSE',
                },
                {
                    id: 105,
                    subjectName: 'Competitive Programming Lab',
                    subjectCode: 'CS301L',
                    sectionName: 'CSE-A',
                    semester: 3,
                    hoursPerWeek: 4,
                    studentCount: 30,
                    department: 'CSE',
                },
            ],
        },
        {
            id: 2,
            facultyName: 'Prof. Karthik Subramanian',
            employeeId: 'CSE002',
            designation: 'Assistant Professor',
            department: 'CSE',
            profilePhoto: null,
            totalHoursPerWeek: 24,
            maxHoursPerWeek: 20,
            status: 'OVERLOADED',
            attendanceAvg: 87.2,
            pendingGradingCount: 7,
            courseAssignments: [
                {
                    id: 201,
                    subjectName: 'Database Management Systems',
                    subjectCode: 'CS401',
                    sectionName: 'CSE-A',
                    semester: 4,
                    hoursPerWeek: 4,
                    studentCount: 62,
                    department: 'CSE',
                },
                {
                    id: 202,
                    subjectName: 'Database Management Systems',
                    subjectCode: 'CS401',
                    sectionName: 'CSE-B',
                    semester: 4,
                    hoursPerWeek: 4,
                    studentCount: 58,
                    department: 'CSE',
                },
                {
                    id: 203,
                    subjectName: 'DBMS Lab',
                    subjectCode: 'CS401L',
                    sectionName: 'CSE-A',
                    semester: 4,
                    hoursPerWeek: 4,
                    studentCount: 31,
                    department: 'CSE',
                },
                {
                    id: 204,
                    subjectName: 'DBMS Lab',
                    subjectCode: 'CS401L',
                    sectionName: 'CSE-B',
                    semester: 4,
                    hoursPerWeek: 4,
                    studentCount: 29,
                    department: 'CSE',
                },
                {
                    id: 205,
                    subjectName: 'Big Data Analytics',
                    subjectCode: 'CS601',
                    sectionName: 'CSE-A',
                    semester: 6,
                    hoursPerWeek: 4,
                    studentCount: 60,
                    department: 'CSE',
                },
                {
                    id: 206,
                    subjectName: 'Big Data Analytics',
                    subjectCode: 'CS601',
                    sectionName: 'CSE-B',
                    semester: 6,
                    hoursPerWeek: 4,
                    studentCount: 57,
                    department: 'CSE',
                },
            ],
        },
        {
            id: 3,
            facultyName: 'Dr. Meena Krishnaswamy',
            employeeId: 'CSE003',
            designation: 'Professor',
            department: 'CSE',
            profilePhoto: null,
            totalHoursPerWeek: 18,
            maxHoursPerWeek: 20,
            status: 'OPTIMAL',
            attendanceAvg: 95.0,
            pendingGradingCount: 1,
            courseAssignments: [
                {
                    id: 301,
                    subjectName: 'Theory of Computation',
                    subjectCode: 'CS502',
                    sectionName: 'CSE-A',
                    semester: 5,
                    hoursPerWeek: 4,
                    studentCount: 60,
                    department: 'CSE',
                },
                {
                    id: 302,
                    subjectName: 'Theory of Computation',
                    subjectCode: 'CS502',
                    sectionName: 'CSE-B',
                    semester: 5,
                    hoursPerWeek: 4,
                    studentCount: 55,
                    department: 'CSE',
                },
                {
                    id: 303,
                    subjectName: 'Compiler Design',
                    subjectCode: 'CS602',
                    sectionName: 'CSE-A',
                    semester: 6,
                    hoursPerWeek: 5,
                    studentCount: 60,
                    department: 'CSE',
                },
                {
                    id: 304,
                    subjectName: 'Compiler Design Lab',
                    subjectCode: 'CS602L',
                    sectionName: 'CSE-A',
                    semester: 6,
                    hoursPerWeek: 5,
                    studentCount: 30,
                    department: 'CSE',
                },
            ],
        },
        {
            id: 4,
            facultyName: 'Mr. Suresh Venkataraman',
            employeeId: 'CSE004',
            designation: 'Assistant Professor',
            department: 'CSE',
            profilePhoto: null,
            totalHoursPerWeek: 16,
            maxHoursPerWeek: 20,
            status: 'OPTIMAL',
            attendanceAvg: 89.5,
            pendingGradingCount: 2,
            courseAssignments: [
                {
                    id: 401,
                    subjectName: 'Computer Networks',
                    subjectCode: 'CS503',
                    sectionName: 'CSE-A',
                    semester: 5,
                    hoursPerWeek: 4,
                    studentCount: 60,
                    department: 'CSE',
                },
                {
                    id: 402,
                    subjectName: 'Computer Networks',
                    subjectCode: 'CS503',
                    sectionName: 'CSE-B',
                    semester: 5,
                    hoursPerWeek: 4,
                    studentCount: 55,
                    department: 'CSE',
                },
                {
                    id: 403,
                    subjectName: 'Networks Lab',
                    subjectCode: 'CS503L',
                    sectionName: 'CSE-B',
                    semester: 5,
                    hoursPerWeek: 4,
                    studentCount: 28,
                    department: 'CSE',
                },
                {
                    id: 404,
                    subjectName: 'Networks Lab',
                    subjectCode: 'CS503L',
                    sectionName: 'CSE-A',
                    semester: 5,
                    hoursPerWeek: 4,
                    studentCount: 30,
                    department: 'CSE',
                },
            ],
        },
        {
            id: 5,
            facultyName: 'Dr. Priya Narayanan',
            employeeId: 'CSE005',
            designation: 'Associate Professor',
            department: 'CSE',
            profilePhoto: null,
            totalHoursPerWeek: 18,
            maxHoursPerWeek: 20,
            status: 'OPTIMAL',
            attendanceAvg: 93.1,
            pendingGradingCount: 0,
            courseAssignments: [
                {
                    id: 501,
                    subjectName: 'Machine Learning',
                    subjectCode: 'CS701',
                    sectionName: 'CSE-A',
                    semester: 7,
                    hoursPerWeek: 4,
                    studentCount: 58,
                    department: 'CSE',
                },
                {
                    id: 502,
                    subjectName: 'Machine Learning',
                    subjectCode: 'CS701',
                    sectionName: 'CSE-B',
                    semester: 7,
                    hoursPerWeek: 4,
                    studentCount: 54,
                    department: 'CSE',
                },
                {
                    id: 503,
                    subjectName: 'ML Lab',
                    subjectCode: 'CS701L',
                    sectionName: 'CSE-A',
                    semester: 7,
                    hoursPerWeek: 5,
                    studentCount: 30,
                    department: 'CSE',
                },
                {
                    id: 504,
                    subjectName: 'ML Lab',
                    subjectCode: 'CS701L',
                    sectionName: 'CSE-B',
                    semester: 7,
                    hoursPerWeek: 5,
                    studentCount: 27,
                    department: 'CSE',
                },
            ],
        },
        {
            id: 6,
            facultyName: 'Mr. Balamurugan Pandi',
            employeeId: 'CSE006',
            designation: 'Assistant Professor',
            department: 'CSE',
            profilePhoto: null,
            totalHoursPerWeek: 20,
            maxHoursPerWeek: 20,
            status: 'OPTIMAL',
            attendanceAvg: 88.0,
            pendingGradingCount: 4,
            courseAssignments: [
                {
                    id: 601,
                    subjectName: 'Operating Systems',
                    subjectCode: 'CS403',
                    sectionName: 'CSE-A',
                    semester: 4,
                    hoursPerWeek: 5,
                    studentCount: 62,
                    department: 'CSE',
                },
                {
                    id: 602,
                    subjectName: 'Operating Systems',
                    subjectCode: 'CS403',
                    sectionName: 'CSE-B',
                    semester: 4,
                    hoursPerWeek: 5,
                    studentCount: 58,
                    department: 'CSE',
                },
                {
                    id: 603,
                    subjectName: 'OS Lab',
                    subjectCode: 'CS403L',
                    sectionName: 'CSE-A',
                    semester: 4,
                    hoursPerWeek: 5,
                    studentCount: 31,
                    department: 'CSE',
                },
                {
                    id: 604,
                    subjectName: 'OS Lab',
                    subjectCode: 'CS403L',
                    sectionName: 'CSE-B',
                    semester: 4,
                    hoursPerWeek: 5,
                    studentCount: 29,
                    department: 'CSE',
                },
            ],
        },
        {
            id: 7,
            facultyName: 'Dr. Lakshmi Selvaraj',
            employeeId: 'CSE007',
            designation: 'Associate Professor',
            department: 'CSE',
            profilePhoto: null,
            totalHoursPerWeek: 14,
            maxHoursPerWeek: 20,
            status: 'OPTIMAL',
            attendanceAvg: 97.2,
            pendingGradingCount: 0,
            courseAssignments: [
                {
                    id: 701,
                    subjectName: 'Software Engineering',
                    subjectCode: 'CS504',
                    sectionName: 'CSE-A',
                    semester: 5,
                    hoursPerWeek: 4,
                    studentCount: 60,
                    department: 'CSE',
                },
                {
                    id: 702,
                    subjectName: 'Software Engineering',
                    subjectCode: 'CS504',
                    sectionName: 'CSE-B',
                    semester: 5,
                    hoursPerWeek: 4,
                    studentCount: 55,
                    department: 'CSE',
                },
                {
                    id: 703,
                    subjectName: 'Soft Skills for Engineers',
                    subjectCode: 'HS301',
                    sectionName: 'CSE-A',
                    semester: 3,
                    hoursPerWeek: 3,
                    studentCount: 62,
                    department: 'CSE',
                },
                {
                    id: 704,
                    subjectName: 'Soft Skills for Engineers',
                    subjectCode: 'HS301',
                    sectionName: 'CSE-B',
                    semester: 3,
                    hoursPerWeek: 3,
                    studentCount: 58,
                    department: 'CSE',
                },
            ],
        },
        {
            id: 8,
            facultyName: 'Mr. Dinesh Ramasamy',
            employeeId: 'CSE008',
            designation: 'Assistant Professor',
            department: 'CSE',
            profilePhoto: null,
            totalHoursPerWeek: 8,
            maxHoursPerWeek: 20,
            status: 'UNDERLOADED',
            attendanceAvg: 82.5,
            pendingGradingCount: 1,
            courseAssignments: [
                {
                    id: 801,
                    subjectName: 'Web Technology',
                    subjectCode: 'CS402',
                    sectionName: 'CSE-A',
                    semester: 4,
                    hoursPerWeek: 4,
                    studentCount: 62,
                    department: 'CSE',
                },
                {
                    id: 802,
                    subjectName: 'Professional Ethics',
                    subjectCode: 'GE301',
                    sectionName: 'CSE-A',
                    semester: 5,
                    hoursPerWeek: 2,
                    studentCount: 60,
                    department: 'CSE',
                },
                {
                    id: 803,
                    subjectName: 'Professional Ethics',
                    subjectCode: 'GE301',
                    sectionName: 'CSE-B',
                    semester: 5,
                    hoursPerWeek: 2,
                    studentCount: 55,
                    department: 'CSE',
                },
            ],
        },
    ],
};
